// Code generated by /tmp/extract_checkpoints.py — manually re-runnable.
// Source: github.com/kinoz01/zone01-Piscine/v2/checkpoint (exam exercises).
//
// Checkpoints are the standalone programs students must implement during
// the Piscine exam. They mostly live in package main with arg/stdin I/O,
// so the embedded solutions are the FULL main.go a grader compiles.

package knowledge

func init() {
	Exercises = append(Exercises, checkpointExercises...)
}

// checkpointExercises holds 30 Piscine checkpoint/exam tasks.
var checkpointExercises = []Exercise{
	{
		Name:        "brackets",
		DisplayName: "CheckBrackets",
		Signature:   "func CheckBrackets(s string) bool",
		Solution: `package main

import "os"

func main() {
	if len(os.Args) <= 1 {
		return
	}

	for _, str := range os.Args[1:] {
		if CheckBrackets(str) {
			os.Stdout.WriteString("OK\n")
		} else {
			os.Stdout.WriteString("Error\n")
		}
	}

}

func CheckBrackets(s string) bool {
	bra := map[rune]rune {
		')': '(',
		']': '[',
		'}': '{',
	}

	var stack []rune
	for _, char := range s {
		switch char{
		case '(', '{', '[':
			stack = append(stack, char)
		case ')', '}', ']':
			if len(stack) == 0 || stack[len(stack)-1] != bra[char] {
				return false
			}
			stack = stack[:len(stack)-1]
		}
	}
	return len(stack) == 0
}`,
		Description: "Проверка сбалансированности скобок (), [], {} в строке. Классическая задача со стеком.",
		Concepts:    []string{"brackets", "checkpoint", "exam"},
	},
	{
		Name:        "cameltosnakecase",
		DisplayName: "CamelToSnakeCase",
		Signature:   "func CamelToSnakeCase(s string) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(CamelToSnakeCase("HelloWorld"))
	fmt.Println(CamelToSnakeCase("helloWorld"))
	fmt.Println(CamelToSnakeCase("camelCase"))
	fmt.Println(CamelToSnakeCase("CAMELtoSnackCASE"))
	fmt.Println(CamelToSnakeCase("camelToSnakeCase"))
	fmt.Println(CamelToSnakeCase("hey2"))
}

func CamelToSnakeCase(s string) string {
	if s == "" {
		return ""
	}
	if !CheckIfCamel(s) {
		return s
	}

	return CamelToSnake(s)
}

func CheckIfCamel(s string) bool {
	r := []rune(s)
	if r[len(r)-1] >= 'A' && r[len(r)-1] <= 'Z' {
		return false
	}
	for i, char := range s {
		if (char < 'a' || char > 'z') && (char < 'A' || char > 'Z') {
			return false
		}
		if i+1 < len(s) && (char >= 'A' && char <= 'Z') && (s[i+1] >= 'A' && s[i+1] <= 'Z') {
			return false
		}
	}
	return true
}

func CamelToSnake(s string) string {
	rSlice := []rune{}
	r := []rune(s)
	for i, char := range r {
		rSlice = append(rSlice, char)
		if i+1 < len(r) && r[i+1] >= 'A' && r[i+1] <= 'Z' {
			rSlice = append(rSlice, '_')
		}
	}
	return string(rSlice)
}`,
		Description: "Конвертация camelCase в snake_case: каждая заглавная буква → _ + строчная.",
		Concepts:    []string{"cameltosnakecase", "checkpoint", "exam", "регистр", "case"},
	},
	{
		Name:        "canjump",
		DisplayName: "CanJump",
		Signature:   "func CanJump(steps []uint) bool",
		Solution: `package main

import (
	"checkpoint/canjump/solution"
	"fmt"
)

func main() {
	fmt.Println(CanJump([]uint{0}))
	fmt.Println(solution.CanJump([]uint{0}))
}

func CanJump(steps []uint) bool {
	if len(steps) == 0 {
		return false
	}
	MaxReach := 0
	for i, n := range steps {
		if n != 0 {
			MaxReach = i + int(n)
		}
		if MaxReach == len(steps)-1 || len(steps) == 1 {
			return true
		}
	}
	return false
}`,
		Description: "Можно ли допрыгать до конца массива если в каждой ячейке максимальная длина прыжка. Жадный алгоритм.",
		Concepts:    []string{"canjump", "checkpoint", "exam"},
	},
	{
		Name:        "checknumber",
		DisplayName: "CheckNumber",
		Signature:   "func CheckNumber(arg string) bool",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(CheckNumber("Hello"))
	fmt.Println(CheckNumber("Hello1"))
}

func CheckNumber(arg string) bool {
	for _, r := range arg {
		if r <= '9' && r >= '0' {
			return true
		}
	}
	return false
}`,
		Description: "Проверка числа на специфические условия (палиндром, простота, и т.п. — зависит от варианта).",
		Concepts:    []string{"checknumber", "checkpoint", "exam", "число", "number", "конвертация"},
	},
	{
		Name:        "concatalternate",
		DisplayName: "ConcatAlternate",
		Signature:   "func ConcatAlternate(slice1, slice2 []int) []int",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))
	fmt.Println(ConcatAlternate([]int{2, 4, 6, 8, 10}, []int{1, 3, 5, 7, 9, 11}))
	fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6, 7, 8, 9}))
	fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{}))
}

func ConcatAlternate(slice1, slice2 []int) []int {
	result := []int{}
	if len(slice1) < len(slice2) {
		slice1, slice2 = slice2, slice1
	}
	for i, n := range slice1 {
		result = append(result, n)
		if i < len(slice2) {
			result = append(result, slice2[i])
		}
	}
	return result
}`,
		Description: "Соединяет два слайса чередуя элементы: a[0], b[0], a[1], b[1]...",
		Concepts:    []string{"concatalternate", "checkpoint", "exam", "конкатенация", "concat"},
	},
	{
		Name:        "concatslice",
		DisplayName: "ConcatSlice",
		Signature:   "func ConcatSlice(slice1, slice2 []int) (result []int)",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(ConcatSlice([]int{1, 2, 3}, []int{4, 5, 6}))
	fmt.Println(ConcatSlice([]int{}, []int{4, 5, 6, 7, 8, 9}))
	fmt.Println(ConcatSlice([]int{1, 2, 3}, []int{}))
}

func ConcatSlice(slice1, slice2 []int) (result []int) {
	result = append(result, slice1...)
	result = append(result, slice2...)
	return result
}`,
		Description: "Объединяет два слайса в один. Базовый append/copy паттерн.",
		Concepts:    []string{"concatslice", "checkpoint", "exam", "конкатенация", "concat", "слайс", "slice"},
	},
	{
		Name:        "countalpha",
		DisplayName: "CountAlpha",
		Signature:   "func CountAlpha(s string) int",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(CountAlpha("Hello world"))
	fmt.Println(CountAlpha("H e l l o"))
	fmt.Println(CountAlpha("H1e2l3l4o"))
}

func CountAlpha(s string) int {
	c := 0
	for _, char := range s {
		if (char >= 'a' && char<= 'z') || (char >= 'A' && char<= 'Z') {
			c++
		}
	}
	return c
}`,
		Description: "Считает количество буквенных символов в строке.",
		Concepts:    []string{"countalpha", "checkpoint", "exam"},
	},
	{
		Name:        "fifthandskip",
		DisplayName: "FifthAndSkip",
		Signature:   "func FifthAndSkip(str string) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Print(FifthAndSkip("abcdefghijklmnopqrstuwxyz"))
	fmt.Print(FifthAndSkip("This is a short sentence"))
	fmt.Print(FifthAndSkip("1234"))
}

func FifthAndSkip(str string) string {
	if str == "" {
		return "\n"
	}
	if len(str) < 5 {
		return "Invalid Input\n"
	}
	str = RemoveSpace(str)
	var result string
	
	for i, char := range []rune(str) {
		if (i-5)%6 == 0 && i!=0{
			result += " "
			continue
		}
		result += string(char)
		
	}
	return result+"\n"
}

func RemoveSpace(s string) string {
	r := ""
	for _, char := range s {
		if char == ' ' {
			continue
		}
		r += string(char)
	}
	return r
}`,
		Description: "Печатает каждый 5-й аргумент командной строки, остальные пропускает.",
		Concepts:    []string{"fifthandskip", "checkpoint", "exam"},
	},
	{
		Name:        "grouping",
		DisplayName: "Grouping",
		Signature:   "func Split(s string, sep rune, field bool) (res []string)",
		Solution: `package main

import (
	"os"
)

func main() {
	if len(os.Args[1:]) != 2 || len(os.Args[1]) < 2 || len(os.Args[2]) == 0 {
		return
	}

	if os.Args[1][0] != '(' || os.Args[1][len([]rune(os.Args[1]))-1] != ')' {
		return
	}

	s := Split(os.Args[1][1:len([]rune(os.Args[1]))-1], '|', false)
	if s == nil {
		return
	}
	f := Split(os.Args[2], ' ', true)

	result := []string{}

	for _, word := range f {
		for _, reg := range s {
			if Contains(word, reg) {
				if IsNotLetter(rune(word[len(word)-1])) {
					result = append(result, word[0:len(word)-1])
				} else {
					result = append(result, word)
				}
			}
		}
	}
	for i, w := range result {
		os.Stdout.WriteString(Itoi(i+1) + ": " + w + "\n")
	}
}

func Split(s string, sep rune, field bool) (res []string) {

	if s == "" {
		return nil
	}
	var temp []rune
	for _, r := range s {
		if r == sep {
			res = append(res, string(temp))
			temp = nil
			continue
		}
		temp = append(temp, r)
	}
	res = append(res, string(temp))

	if field {
		temp := res
		res = nil
		for _, str := range temp {
			if str != "" {
				res = append(res, str)
			}
		}
		return res
	}
	return res
}

func IsNotLetter(r rune) bool {
	return !((r <= 'z' && r >= 'a') || (r <= 'Z' && r >= 'A'))
}

func Itoi(n int) (s string) {
	for n > 0 {
		s = string(rune(n%10)+'0') + s
		n /= 10
	}
	return s
}

func Contains(s string, reg string) bool {
	for i := 0; i <= len(s)-len(reg); i++ {
		if s[i:i+len(reg)] == reg {
			return true
		}
	}
	return false
}`,
		Description: "Группирует элементы слайса по некоторому критерию (часто map[K][]V).",
		Concepts:    []string{"grouping", "checkpoint", "exam"},
	},
	{
		Name:        "iscapitalized",
		DisplayName: "IsCapitalized",
		Signature:   "func IsCapitalized(s string) bool",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(IsCapitalized("Hello! How are you?"))
	fmt.Println(IsCapitalized("Hello How Are You"))
	fmt.Println(IsCapitalized("Whats 4this 100K?"))
	fmt.Println(IsCapitalized("Whatsthis4"))
	fmt.Println(IsCapitalized("!!!!Whatsthis4"))
	fmt.Println(IsCapitalized(""))
}

func IsCapitalized(s string) bool {
	if s == "" {
		return false
	}
	words := Fields(s, ' ')
	for _, str := range words {
		if str[0] >= 'a' && str[0] <= 'z' {
			return false
		}
	}
	return true
}

func Fields(s string, sep rune) (res []string) {

	if s == "" {
		return nil
	}
	var stack []rune
	for _, r := range s {
		if r == sep && len(stack) > 0 {
			res = append(res, string(stack))
			stack = nil
			continue
		}
		stack = append(stack, r)
	}
	if len(stack)>0 {
		res = append(res, string(stack))
	}
	
	return res
}`,
		Description: "Проверяет начинается ли строка с заглавной буквы.",
		Concepts:    []string{"iscapitalized", "checkpoint", "exam", "проверка"},
	},
	{
		Name:        "itoa",
		DisplayName: "Itoa",
		Signature:   "func Itoa(n int) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(Itoa(12345))
	fmt.Println(Itoa(0))
	fmt.Println(Itoa(-1234))
	fmt.Println(Itoa(987654321))
}

func Itoa(n int) string {
	if n == 0 {
		return "0"
	}
	s := ""
	var neg bool
	if n < 0 {
		neg = true
		n = -n
	}
	for n > 0 {
		s = string(rune(n%10)+'0') + s
		n /= 10
	}
	if neg {
		return "-" + s
	}
	return s
}`,
		Description: "Integer-to-ASCII: конвертирует int в строку (обратное к Atoi).",
		Concepts:    []string{"itoa", "checkpoint", "exam", "число", "number", "конвертация"},
	},
	{
		Name:        "itoabase",
		DisplayName: "ItoaBase",
		Signature:   "func ItoaBase(n, base int) string",
		Solution: `package main

func main() {

}

func ItoaBase(n, base int) string {
	if base < 2 || base > 16 {
		return ""
	}

	// Characters for digits in base systems
	digits := []rune{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'}

	// Handle negative numbers
	negative := false
	var num uint64

	// Handle negative numbers without overflow
	if n < 0 {
		negative = true
		// Hardcode the value for -9223372036854775808 as uint64
		if n == -9223372036854775808 {
			num = 9223372036854775808 // This is uint64 and correct
		} else {
			num = uint64(-n)
		}
	} else {
		num = uint64(n)
	}

	var result string

	// Convert the number to the specified base
	for num > 0 {
		result = string(digits[num%uint64(base)]) + result
		num /= uint64(base)
	}

	// Add a minus sign for negative numbers
	if negative {
		result = "-" + result
	}

	return result
}`,
		Description: "Конвертирует int в строку в произвольной системе счисления.",
		Concepts:    []string{"itoabase", "checkpoint", "exam", "число", "number", "конвертация"},
	},
	{
		Name:        "notdecimal",
		DisplayName: "NotDecimal",
		Signature:   "func NotDecimal(dec string) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Print(NotDecimal("0.1"))
	fmt.Print(NotDecimal("174.2"))
	fmt.Print(NotDecimal("0.1255"))
	fmt.Print(NotDecimal("1.20525856"))
	fmt.Print(NotDecimal("-0.0f00d00"))
	fmt.Print(NotDecimal(""))
	fmt.Print(NotDecimal("-19.525856"))
	fmt.Print(NotDecimal("1952"))
}

func NotDecimal(dec string) string {
	if dec == "" {
		return "\n"
	}
	if quit := CheckNum(dec); quit {
		return dec +"\n"
	}
	num := ""
	for _, char := range dec {
		if char == '.' {
			continue
		}
		num += string(char)
	}
	return Itoa(Atoi(num))+"\n"
}

func Atoi(s string)int {
	var n int
	sliceS := []rune(s)
	first := true
	for i := 0; i < len(sliceS); i++ {
		if (sliceS[0] == '-' || sliceS[0] == '+') && first {
			first = false
			continue
		}
		if sliceS[i] > '9' || sliceS[i] < '0' {
			return 0
		}
		n = n*10 + int(sliceS[i]-'0')
	}
	if sliceS[0] == '-' {
		return -n
	}
	return n
}

func Itoa(n int) string {
	if n == 0 {
		return "0"
	}
	s := ""
	var neg bool
	if n < 0 {
		neg = true
		n = -n
	}
	for n > 0 {
		s = string(rune(n%10)+'0') + s
		n /= 10
	}
	if neg {
		return "-" + s
	}
	return s
}

func CheckNum(s string) bool {
	if s[0] == '-' {
		s = s[1:]
	}
	if s[0] == '.' {
		return true
	}
	ptFound := false
	for _, char := range s {
		if char == '.' && !ptFound{
			ptFound =true
			continue
		}
		if char < '0' || char > '9' {
			return true
		}
	}
	return false
}`,
		Description: "Возвращает true если в строке нет десятичных цифр (0-9).",
		Concepts:    []string{"notdecimal", "checkpoint", "exam"},
	},
	{
		Name:        "only1",
		DisplayName: "Only1",
		Signature:   "// main program (no exported func)",
		Solution: `package main

import "github.com/01-edu/z01"

func main() {
	z01.PrintRune('1')
}`,
		Description: "Печатает строку с заменой определённых символов на '1'.",
		Concepts:    []string{"only1", "checkpoint", "exam"},
	},
	{
		Name:        "onlyb",
		DisplayName: "OnlyB",
		Signature:   "// main program (no exported func)",
		Solution: `package main

import "github.com/01-edu/z01"

func main() {
	z01.PrintRune('b')
}`,
		Description: "Печатает строку, заменяя все буквы кроме 'b' пробелами.",
		Concepts:    []string{"onlyb", "checkpoint", "exam"},
	},
	{
		Name:        "onlyf",
		DisplayName: "OnlyF",
		Signature:   "// main program (no exported func)",
		Solution: `package main

import "github.com/01-edu/z01"

func main() {
	z01.PrintRune('f')
}`,
		Description: "Печатает строку, заменяя все буквы кроме 'f' пробелами.",
		Concepts:    []string{"onlyf", "checkpoint", "exam"},
	},
	{
		Name:        "printrevcomb",
		DisplayName: "PrintRevComb",
		Signature:   "// main program (no exported func)",
		Solution: `package main

import "github.com/01-edu/z01"

func main() {
	for i := '9'; i >= '0'; i-- {
		for j := '9'; j >= '0'; j-- {
			for k := '9'; k >= '0'; k-- {
				if i <= j || j <= k {
					continue
				}
				z01.PrintRune(i)
				z01.PrintRune(j)
				z01.PrintRune(k)
				if i == '2' && j == '1' && k == '0' {
					break
				}
				z01.PrintRune(',')
				z01.PrintRune(' ')
			}
		}
	}
	z01.PrintRune('\n')
}`,
		Description: "Печатает комбинации в обратном порядке относительно printcomb.",
		Concepts:    []string{"printrevcomb", "checkpoint", "exam", "печать", "print", "комбинации", "combinations", "разворот", "reverse"},
	},
	{
		Name:        "revconcatalternate",
		DisplayName: "RevConcatAlternate",
		Signature:   "func RevConcatAlternate(slice1,slice2 []int) []int",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(RevConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))
	fmt.Println(RevConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6, 7, 8, 9}))
	fmt.Println(RevConcatAlternate([]int{1, 2, 3, 9, 8}, []int{4, 5}))
	fmt.Println(RevConcatAlternate([]int{1, 2, 3}, []int{}))
}

func RevConcatAlternate(slice1,slice2 []int) []int {
	len1 := len(slice1)
	len2 := len(slice2)
	maxLen := len1
	result := []int{}
	if len2 > maxLen {
		maxLen = len2
	}
	for i := maxLen; i >= 0; i-- {
		if i < len1 {
			result = append(result, slice1[i])
		}
		if i < len2 {
			result = append(result, slice2[i])
		}
	}
	return result
}`,
		Description: "Обратный вариант concatalternate: концы слайсов идут первыми.",
		Concepts:    []string{"revconcatalternate", "checkpoint", "exam", "конкатенация", "concat", "разворот", "reverse"},
	},
	{
		Name:        "rpncalc",
		DisplayName: "RPNCalc",
		Signature:   "// main program (no exported func)",
		Solution: `package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

func deleteExtraSpaces(a []string) (res []string) {
	for _, v := range a {
		if v != "" {
			res = append(res, v)
		}
	}
	return
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Error")
		return
	}
	var values []int
	op := strings.Split(os.Args[1], " ")
	op = deleteExtraSpaces(op)
	for _, v := range op {
		val, err := strconv.Atoi(v)

		if err == nil {
			values = append(values, val)
			continue
		}

		n := len(values)
		if n < 2 {
			fmt.Println("Error")
			return
		}

		switch v {
		case "+":
			values[n-2] += values[n-1]
			values = values[:n-1]
		case "-":
			values[n-2] -= values[n-1]
			values = values[:n-1]
		case "*":
			values[n-2] *= values[n-1]
			values = values[:n-1]
		case "/":
			values[n-2] /= values[n-1]
			values = values[:n-1]
		case "%":
			values[n-2] %= values[n-1]
			values = values[:n-1]
		default:
			fmt.Println("Error")
			return
		}
	}
	if len(values) == 1 {
		fmt.Println(values[0])
	} else {
		fmt.Println("Error")
	}
}`,
		Description: "Reverse Polish Notation calculator: вычисляет выражение в постфиксной записи через стек.",
		Concepts:    []string{"rpncalc", "checkpoint", "exam", "калькулятор", "calculator", "expression"},
	},
	{
		Name:        "saveandmiss",
		DisplayName: "SaveAndMiss",
		Signature:   "func SaveAndMiss(arg string, num int) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(SaveAndMiss("123456789", 3))
	fmt.Println(SaveAndMiss("abcdefghijklmnopqrstuvwyz", 3))
	fmt.Println(SaveAndMiss("", 3))
	fmt.Println(SaveAndMiss("hello you all ! ", 0))
	fmt.Println(SaveAndMiss("what is your name?", 0))
	fmt.Println(SaveAndMiss("go Exercise Save and Miss", -5))
	fmt.Println(SaveAndMiss("e 5£ @ 8* 7 =56 ;", 2))
}

func SaveAndMiss(arg string, num int) string {
	if num <= 0 || num > len(arg) {
		return arg
	}

	str := ""
	for i :=0; i<len(arg); i++ {
		if i!=0 && i%num == 0 {
			i += num
			if i>len(arg){
				break
			}
		}
		str += string(rune(arg[i]))
	}
	return str
}`,
		Description: "Печатает аргументы через один: первый, пропустить, третий, пропустить...",
		Concepts:    []string{"saveandmiss", "checkpoint", "exam"},
	},
	{
		Name:        "slice",
		DisplayName: "Slice",
		Signature:   "func Slice(a []string, nbrs ...int) []string",
		Solution: `package main

import (
	"fmt"
	//"checkpoint/slice/solution"
	"github.com/01-edu/go-tests/solutions"
)

func main() {
	a := []string{"coding", "algorithm", "ascii", "package", "golang"}
	fmt.Printf("%#v\n", solutions.Slice(a, 1))
	fmt.Printf("%#v\n", solutions.Slice(a, 1, 10))
	fmt.Printf("%#v\n", solutions.Slice(a, -3))
	fmt.Printf("%#v\n", solutions.Slice(a, -2, 1))
	fmt.Printf("%#v\n", solutions.Slice(a, 2, 0))
}

func Slice(a []string, nbrs ...int) []string {
	if len(nbrs) == 0 {
		return a
	}

	first := nbrs[0]
	if len(nbrs) == 1 {
		if first < 0 {
			first = len(a) + first
			if first < 0 {
				return a
			}
		}
		return a[first:]
	}
	second := nbrs[1]

	first = isNegative(a, first)
	second = isNegative(a, second)

	if first > second {
		return nil
	}
	return a[first:second]
}

func isNegative(a []string, n int) int {
	if n < 0 {
		n = len(a) + n
	}
	if n < 0 {
		n = 0
	} else if n > len(a) {
		n = len(a)
	}
	return n

}`,
		Description: "Возвращает подслайс между двумя индексами (start inclusive, end exclusive).",
		Concepts:    []string{"slice", "checkpoint", "exam", "слайс"},
	},
	{
		Name:        "thirdtimeisacharm",
		DisplayName: "ThirdTimeIsACharm",
		Signature:   "func ThirdTimeIsACharm(str string) string",
		Solution: `package main

import "fmt"

func main() {
	fmt.Print(ThirdTimeIsACharm("123456789"))
	fmt.Print(ThirdTimeIsACharm(""))
	fmt.Print(ThirdTimeIsACharm("a b c d e f"))
	fmt.Print(ThirdTimeIsACharm("12"))
}

func ThirdTimeIsACharm(str string) string {
	var r []rune
	for i, char := range str {
		if (i-2)%3 == 0 {
			r = append(r, char)
		}
	}
	return string(r) + "\n"
}`,
		Description: "Печатает каждое третье вхождение символа в строке.",
		Concepts:    []string{"thirdtimeisacharm", "checkpoint", "exam"},
	},
	{
		Name:        "weareunique",
		DisplayName: "WeAreUnique",
		Signature:   "func WeAreUnique(str1, str2 string) int",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(WeAreUnique("foo", "boo"))
	fmt.Println(WeAreUnique("", ""))
	fmt.Println(WeAreUnique("abc", "def"))
	fmt.Println(WeAreUnique("26235e50", "4478q92"))
}

func WeAreUnique(str1, str2 string) int {
	if str1 == "" && str2 ==""{
		return -1
	}

	res := []rune{}
	for _, char := range str1 {
		if StrContainsChar(char, str2) {
			continue
		} else if !StrContainsChar(char, string(res)) {
			res = append(res, char)
		}
	}
	for _, char := range str2 {
		if StrContainsChar(char, str1) {
			continue
		} else if !StrContainsChar(char, string(res)) {
			res = append(res, char)
		}
	}
	return len(res)
}

func StrContainsChar(r rune, s string) bool {
	for _, char := range s {
		if char == r {
			return true
		}
	}
	return false
}`,
		Description: "Проверяет что все символы в строке уникальны.",
		Concepts:    []string{"weareunique", "checkpoint", "exam"},
	},
	{
		Name:        "wordflip",
		DisplayName: "WordFlip",
		Signature:   "func WordFlip(str string) string",
		Solution: `package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Print(WordFlip("First second last"))
	fmt.Print(WordFlip(""))
	fmt.Print(WordFlip("     "))
	fmt.Print(WordFlip(" hello  all  of  you! "))
}

func WordFlip(str string) string {
	if str == "" {
		return "Invalid Output"
	}
	a := strings.Fields(str)
	result := ""
	if len(a) < 1 {
		return "\n"
	}
	for i := len(a) - 1; i >= 0; i-- {
		result += a[i] + " "
	}
	return result[:len(result)-1] + "\n"
}`,
		Description: "Разворачивает слова в строке: 'hello world' → 'world hello'.",
		Concepts:    []string{"wordflip", "checkpoint", "exam"},
	},
	{
		Name:        "zipstring",
		DisplayName: "ZipString",
		Signature:   "func ZipString(s string) string",
		Solution: `package main

import (
	"fmt"
)

func main() {
	fmt.Println(ZipString("YouuungFellllas"))
	fmt.Println(ZipString("Thee quuick browwn fox juumps over the laaazy dog"))
	fmt.Println(ZipString("Helloo Therre!"))
}

func ZipString(s string) string {
	r := ""
	c := 0
	for i := 0; i < len(s); i += c {
		c = 0
		for j := i; j < len(s); j++ {
			if s[j] != s[i] {
				break
			}
			c++
		}
		r += Itoa(c) + string(s[i])
	}
	return r
}

func Itoa(n int) (s string) {
	for n > 0 {
		s = string(rune(n%10)+'0') + s
		n /= 10
	}
	return s
}`,
		Description: "Сжимает строку как run-length encoding: 'aaabbc' → 'a3b2c1'.",
		Concepts:    []string{"zipstring", "checkpoint", "exam", "строка", "string"},
	},
}
