import type {
  AdminStats,
  AdminUser,
  AdminUserDetails,
  AuditLogEntry,
  PageMeta,
  Paginated,
  RawAdminStats,
  RawAdminUser,
  RawAdminUserDetails,
  RawAuditLogEntry,
} from '@/entities/admin/types';
import { mapSession } from '@/entities/session';
import { toRole } from '@/entities/user';
import { apiClient } from './apiClient';

/**
 * Admin API — typed wrapper for the Go Admin endpoints (/api/v1/admin/*).
 *
 * Every method maps the snake_case backend DTO into the app's camelCase
 * domain model, so call sites never see raw API shapes. Reads are GETs; CSV
 * exports stream backend-generated bytes (no client-side CSV).
 */

/** Default page size for admin listings — mirrors the backend default. */
export const ADMIN_PAGE_SIZE = 20;

/** YYYY-MM-DD range parameters required by the export endpoints. */
export interface ExportRange {
  from: string;
  to: string;
}

/** Sort key accepted by the users listing. "-" prefix means descending. */
export type AdminUserSort =
  | 'created_at'
  | '-created_at'
  | 'current_streak'
  | '-current_streak'
  | 'best_streak'
  | '-best_streak';

// --- raw envelopes -----------------------------------------------------------

interface RawPageMeta {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
}

interface RawPaginated<T> {
  items: T[];
  pagination: RawPageMeta;
}

// --- mappers -----------------------------------------------------------------

function mapStats(r: RawAdminStats): AdminStats {
  return {
    totalUsers: r.total_users,
    activeSessions: r.active_sessions,
    totalStudyHours: r.total_study_hours,
    completedSessions: r.completed_sessions,
    bestStreak: r.best_streak,
    averageStreak: r.average_streak,
    newUsers7d: r.new_users_7d,
  };
}

function mapPageMeta(r: RawPageMeta): PageMeta {
  return { page: r.page, limit: r.limit, total: r.total, totalPages: r.total_pages };
}

function mapAdminUser(r: RawAdminUser): AdminUser {
  return {
    id: r.id,
    telegramId: r.telegram_id,
    username: r.username,
    firstName: r.first_name,
    role: toRole(r.role),
    currentStreak: r.current_streak,
    bestStreak: r.best_streak,
    lastStudyAt: r.last_study_at,
    createdAt: r.created_at,
  };
}

function mapUserDetails(r: RawAdminUserDetails): AdminUserDetails {
  return {
    profile: mapAdminUser(r.profile),
    streak: {
      current: r.streak.current,
      best: r.streak.best,
      lastStudyAt: r.streak.last_study_at,
    },
    totalMinutes: r.total_minutes,
    totalHours: r.total_hours,
    activeSession: r.active_session ? mapSession(r.active_session) : null,
    recentSessions: r.recent_sessions.map(mapSession),
  };
}

function mapAuditLog(r: RawAuditLogEntry): AuditLogEntry {
  return {
    id: r.id,
    adminId: r.admin_id,
    action: r.action,
    entityType: r.entity_type,
    entityId: r.entity_id,
    targetUserId: r.target_user_id,
    reason: r.reason,
    createdAt: r.created_at,
  };
}

export const adminApi = {
  /** GET /api/v1/admin/stats — operational counters. */
  async getStats(signal?: AbortSignal): Promise<AdminStats> {
    return mapStats(await apiClient.get<RawAdminStats>('/admin/stats', { signal }));
  },

  /** GET /api/v1/admin/users — paginated users list with optional search/sort. */
  async listUsers(
    params: { page: number; search?: string; sort?: AdminUserSort },
    signal?: AbortSignal,
  ): Promise<Paginated<AdminUser>> {
    const query = new URLSearchParams({
      page: String(params.page),
      limit: String(ADMIN_PAGE_SIZE),
    });
    if (params.search) query.set('search', params.search);
    if (params.sort) query.set('sort', params.sort);
    const raw = await apiClient.get<RawPaginated<RawAdminUser>>(
      `/admin/users?${query.toString()}`,
      { signal },
    );
    return { items: raw.items.map(mapAdminUser), pagination: mapPageMeta(raw.pagination) };
  },

  /** GET /api/v1/admin/users/{id} — one user's full admin profile. */
  async getUser(id: number, signal?: AbortSignal): Promise<AdminUserDetails> {
    return mapUserDetails(
      await apiClient.get<RawAdminUserDetails>(`/admin/users/${id}`, { signal }),
    );
  },

  /** GET /api/v1/admin/audit-logs — paginated immutable audit log. */
  async listAuditLogs(
    params: { page: number; action?: string },
    signal?: AbortSignal,
  ): Promise<Paginated<AuditLogEntry>> {
    const query = new URLSearchParams({
      page: String(params.page),
      limit: String(ADMIN_PAGE_SIZE),
    });
    if (params.action) query.set('action', params.action);
    const raw = await apiClient.get<RawPaginated<RawAuditLogEntry>>(
      `/admin/audit-logs?${query.toString()}`,
      { signal },
    );
    return { items: raw.items.map(mapAuditLog), pagination: mapPageMeta(raw.pagination) };
  },

  /**
   * GET /api/v1/admin/export/users — backend-generated CSV. The frontend only
   * streams the bytes; it never builds CSV client-side.
   */
  exportUsers(range: ExportRange): Promise<Blob> {
    return apiClient.download(`/admin/export/users?from=${range.from}&to=${range.to}`);
  },

  /** GET /api/v1/admin/export/sessions — backend-generated CSV. */
  exportSessions(range: ExportRange): Promise<Blob> {
    return apiClient.download(`/admin/export/sessions?from=${range.from}&to=${range.to}`);
  },
};
