import type {
  AdminSession,
  AdminStats,
  AdminUser,
  AdminUserDetails,
  AuditLogEntry,
  PageMeta,
  Paginated,
  RawAdminSession,
  RawAdminStats,
  RawAdminUser,
  RawAdminUserDetails,
  RawAuditLogEntry,
  RawSessionCorrectionResult,
  SessionCorrectionResult,
  SessionPatchInput,
} from '@/entities/admin/types';
import { mapSession } from '@/entities/session';
import { toRole } from '@/entities/user';
import { apiClient } from './apiClient';

/**
 * Admin API — typed wrapper for the Go Admin endpoints (/api/v1/admin/*).
 *
 * Every method maps the snake_case backend DTO into the app's camelCase
 * domain model, so call sites never see raw API shapes. Reads are GETs; CSV
 * exports stream backend-generated bytes (no client-side CSV).
 */

/** Default page size for admin listings — mirrors the backend default. */
export const ADMIN_PAGE_SIZE = 20;

/** YYYY-MM-DD range parameters required by the export endpoints. */
export interface ExportRange {
  from: string;
  to: string;
}

/** Sort key accepted by the users listing. "-" prefix means descending. */
export type AdminUserSort =
  | 'created_at'
  | '-created_at'
  | 'current_streak'
  | '-current_streak'
  | 'best_streak'
  | '-best_streak';

// --- raw envelopes -----------------------------------------------------------

interface RawPageMeta {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
}

interface RawPaginated<T> {
  items: T[];
  pagination: RawPageMeta;
}

// --- mappers -----------------------------------------------------------------

function mapStats(r: RawAdminStats): AdminStats {
  return {
    totalUsers: r.total_users,
    activeSessions: r.active_sessions,
    totalStudyHours: r.total_study_hours,
    completedSessions: r.completed_sessions,
    bestStreak: r.best_streak,
    averageStreak: r.average_streak,
    newUsers7d: r.new_users_7d,
  };
}

function mapPageMeta(r: RawPageMeta): PageMeta {
  return { page: r.page, limit: r.limit, total: r.total, totalPages: r.total_pages };
}

function mapAdminUser(r: RawAdminUser): AdminUser {
  return {
    id: r.id,
    telegramId: r.telegram_id,
    username: r.username,
    firstName: r.first_name,
    role: toRole(r.role),
    currentStreak: r.current_streak,
    bestStreak: r.best_streak,
    lastStudyAt: r.last_study_at,
    createdAt: r.created_at,
  };
}

function mapUserDetails(r: RawAdminUserDetails): AdminUserDetails {
  return {
    profile: mapAdminUser(r.profile),
    streak: {
      current: r.streak.current,
      best: r.streak.best,
      lastStudyAt: r.streak.last_study_at,
    },
    totalMinutes: r.total_minutes,
    totalHours: r.total_hours,
    activeSession: r.active_session ? mapSession(r.active_session) : null,
    recentSessions: r.recent_sessions.map(mapSession),
  };
}

function mapAuditLog(r: RawAuditLogEntry): AuditLogEntry {
  return {
    id: r.id,
    adminId: r.admin_id,
    action: r.action,
    entityType: r.entity_type,
    entityId: r.entity_id,
    targetUserId: r.target_user_id,
    reason: r.reason,
    createdAt: r.created_at,
  };
}

function mapAdminSession(r: RawAdminSession): AdminSession {
  return {
    id: r.id,
    userId: r.user_id,
    startedAt: r.started_at,
    endedAt: r.ended_at,
    durationMinutes: r.duration_minutes,
    isActive: r.is_active,
    isValid: r.is_valid,
    antiCheatFlags: r.anti_cheat_flags ?? [],
    ownerFirstName: r.owner_first_name,
    ownerUsername: r.owner_username,
  };
}

// --- broadcasts --------------------------------------------------------------

/** One broadcast — an admin message fan-out to every user. */
export interface Broadcast {
  id: number;
  message: string;
  status: 'running' | 'done';
  totalRecipients: number;
  sentCount: number;
  failedCount: number;
  createdAt: string;
  finishedAt: string | null;
}

interface RawBroadcast {
  id: number;
  message: string;
  status: string;
  total_recipients: number;
  sent_count: number;
  failed_count: number;
  created_at: string;
  finished_at?: string;
}

function mapBroadcast(r: RawBroadcast): Broadcast {
  return {
    id: r.id,
    message: r.message,
    status: r.status === 'done' ? 'done' : 'running',
    totalRecipients: r.total_recipients,
    sentCount: r.sent_count,
    failedCount: r.failed_count,
    createdAt: r.created_at,
    finishedAt: r.finished_at ?? null,
  };
}

export const adminApi = {
  /** GET /api/v1/admin/stats — operational counters. */
  async getStats(signal?: AbortSignal): Promise<AdminStats> {
    return mapStats(await apiClient.get<RawAdminStats>('/admin/stats', { signal }));
  },

  /** GET /api/v1/admin/users — paginated users list with optional search/sort. */
  async listUsers(
    params: { page: number; search?: string; sort?: AdminUserSort },
    signal?: AbortSignal,
  ): Promise<Paginated<AdminUser>> {
    const query = new URLSearchParams({
      page: String(params.page),
      limit: String(ADMIN_PAGE_SIZE),
    });
    if (params.search) query.set('search', params.search);
    if (params.sort) query.set('sort', params.sort);
    const raw = await apiClient.get<RawPaginated<RawAdminUser>>(
      `/admin/users?${query.toString()}`,
      { signal },
    );
    return { items: raw.items.map(mapAdminUser), pagination: mapPageMeta(raw.pagination) };
  },

  /** GET /api/v1/admin/users/{id} — one user's full admin profile. */
  async getUser(id: number, signal?: AbortSignal): Promise<AdminUserDetails> {
    return mapUserDetails(
      await apiClient.get<RawAdminUserDetails>(`/admin/users/${id}`, { signal }),
    );
  },

  /** GET /api/v1/admin/audit-logs — paginated immutable audit log. */
  async listAuditLogs(
    params: { page: number; action?: string },
    signal?: AbortSignal,
  ): Promise<Paginated<AuditLogEntry>> {
    const query = new URLSearchParams({
      page: String(params.page),
      limit: String(ADMIN_PAGE_SIZE),
    });
    if (params.action) query.set('action', params.action);
    const raw = await apiClient.get<RawPaginated<RawAuditLogEntry>>(
      `/admin/audit-logs?${query.toString()}`,
      { signal },
    );
    return { items: raw.items.map(mapAuditLog), pagination: mapPageMeta(raw.pagination) };
  },

  /** GET /api/v1/admin/sessions — paginated sessions list with optional filters. */
  async listSessions(
    params: { page: number; valid?: boolean; flagged?: boolean; userId?: number },
    signal?: AbortSignal,
  ): Promise<Paginated<AdminSession>> {
    const query = new URLSearchParams({
      page: String(params.page),
      limit: String(ADMIN_PAGE_SIZE),
    });
    if (params.valid !== undefined) query.set('valid', String(params.valid));
    if (params.flagged) query.set('flagged', 'true');
    if (params.userId) query.set('user_id', String(params.userId));
    const raw = await apiClient.get<RawPaginated<RawAdminSession>>(
      `/admin/sessions?${query.toString()}`,
      { signal },
    );
    return { items: raw.items.map(mapAdminSession), pagination: mapPageMeta(raw.pagination) };
  },

  /**
   * PATCH /api/v1/admin/sessions/{id} — correct a finished session. The body
   * carries the full editable state plus a mandatory reason; the backend
   * rejects corrections of active sessions (409) and writes an immutable
   * audit record for every change.
   */
  async correctSession(id: number, patch: SessionPatchInput): Promise<SessionCorrectionResult> {
    const raw = await apiClient.patch<RawSessionCorrectionResult>(`/admin/sessions/${id}`, {
      duration_minutes: patch.durationMinutes,
      is_valid: patch.isValid,
      anti_cheat_flags: patch.antiCheatFlags,
      reason: patch.reason,
    });
    return {
      sessionId: raw.session_id,
      streakRecomputed: raw.streak_recomputed,
      currentStreak: raw.current_streak,
      bestStreak: raw.best_streak,
    };
  },

  /**
   * GET /api/v1/admin/export/users — backend-generated CSV. The frontend only
   * streams the bytes; it never builds CSV client-side.
   */
  exportUsers(range: ExportRange): Promise<Blob> {
    return apiClient.download(`/admin/export/users?from=${range.from}&to=${range.to}`);
  },

  /** GET /api/v1/admin/export/sessions — backend-generated CSV. */
  exportSessions(range: ExportRange): Promise<Blob> {
    return apiClient.download(`/admin/export/sessions?from=${range.from}&to=${range.to}`);
  },

  /**
   * POST /api/v1/admin/broadcast — start a message fan-out to every user. The
   * send runs in the background; the returned broadcast carries live counters
   * the caller polls via listBroadcasts. 409 when one is already running.
   */
  async startBroadcast(text: string): Promise<Broadcast> {
    return mapBroadcast(await apiClient.post<RawBroadcast>('/admin/broadcast', { text }));
  },

  /** GET /api/v1/admin/broadcasts — recent broadcasts, newest first. */
  async listBroadcasts(signal?: AbortSignal): Promise<Broadcast[]> {
    const raw = await apiClient.get<RawBroadcast[]>('/admin/broadcasts', { signal });
    return raw.map(mapBroadcast);
  },
};
